export * from './Register';
export * from './Login';
export * from './layouts/HomeLayout';
export * from './layouts/AuthLayout';
export * from './layouts/EmployeesLayout';
export * from './Employees';
export { default as Skills } from './Skills';
export { default as Languages } from './Languages';
export { default as CVs } from './CVs';
export { default as Error } from './Error';
export { default as Settings } from './Settings';
export { default as Profile } from './Profile';
